### ISSUE TITLE
I can not install this plugin

### ISSUE THREAD

**Issue by pedritorod** [ahe/2dc_jqgrid#15]
I don't know if you have the same problem, I looking for an answer, I can make a clone with the app, but I can not install the 2dc_jqgrid ... do you have the same problem.. or do you have any solution, let me know . thanks in advance for your kindness..................
I think rails is a good framework but .....

**Comment by pedritorod** [comment]
no comments....

**Comment by schonarth** [comment]
I also tried installing the plugin and got this message:

rake aborted!
Don't know how to build task 'jqgrid:install'

I am running Rails 3.1.
